main:
  - changed-files:
      - any-glob-to-any-file: "asusrouter/*.py"
modules:
  - changed-files:
      - any-glob-to-any-file: "asusrouter/modules/**"
tools:
  - changed-files:
      - any-glob-to-any-file: "asusrouter/tools/**"
testing:
  - changed-files:
      - any-glob-to-any-file: "tests/**"
documentation:
  - changed-files:
      - any-glob-to-any-file: "docs/**"
      - any-glob-to-any-file: "*.md"
github:
  - changed-files:
      - any-glob-to-any-file: ".github/**"
github_actions:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"
dependencies:
  - changed-files:
      - any-glob-to-any-file: "uv.lock"
      - any-glob-to-any-file: "pyproject.toml"
