codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "0...100"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no

status:
  project:
    default:
      threshold: 1%
  patch:
    default:
      threshold: 1%
