"""Parental control module for AsusRouter."""

from __future__ import annotations

from asusrouter.modules.parental_control.block_all import (
    ARBlockAllAction,
    ARBlockAllSource,
    ARBlockAllSourceUniversal,
)
from asusrouter.modules.parental_control.enums import (
    ARParentalControlCommand,
    ARParentalControlField,
    ARParentalControlScheduleMode,
    ARParentalControlType,
    ARWeekday,
)
from asusrouter.modules.parental_control.legacy import (
    HOOK_PC,
    KEY_PC_BLOCK_ALL,
    KEY_PC_STATE,
    AsusBlockAll,
    AsusParentalControl,
    ParentalControlRule,
    PCRuleType,
    read_pc_rules,
    set_state,
)
from asusrouter.modules.parental_control.schedule import (
    DAILY,
    DEFAULT_MAX_ENTRIES,
    DEFAULT_MAX_RULES,
    DEFAULT_TIMEMAP,
    SCHEDULE_MODE_MIN_VERSION,
    WEEKDAYS,
    WEEKEND,
    ARParentalControlAction,
    ARParentalControlRule,
    ARParentalControlSource,
    ARParentalControlSourceUniversal,
    ARScheduleEntry,
    get_state,
    parse_timemap,
    rule_entry_count,
    rule_schedule_mode,
    run_action,
    serialize_rules,
    serialize_timemap,
    timemap_mode,
    translate_state,
)

__all__ = [
    "DAILY",
    "DEFAULT_MAX_ENTRIES",
    "DEFAULT_MAX_RULES",
    "DEFAULT_TIMEMAP",
    "HOOK_PC",
    "KEY_PC_BLOCK_ALL",
    "KEY_PC_STATE",
    "SCHEDULE_MODE_MIN_VERSION",
    "WEEKDAYS",
    "WEEKEND",
    "ARBlockAllAction",
    "ARBlockAllSource",
    "ARBlockAllSourceUniversal",
    "ARParentalControlAction",
    "ARParentalControlCommand",
    "ARParentalControlField",
    "ARParentalControlRule",
    "ARParentalControlScheduleMode",
    "ARParentalControlSource",
    "ARParentalControlSourceUniversal",
    "ARParentalControlType",
    "ARScheduleEntry",
    "ARWeekday",
    "AsusBlockAll",
    "AsusParentalControl",
    "ParentalControlRule",
    "PCRuleType",
    "get_state",
    "parse_timemap",
    "read_pc_rules",
    "rule_entry_count",
    "rule_schedule_mode",
    "run_action",
    "serialize_rules",
    "serialize_timemap",
    "set_state",
    "timemap_mode",
    "translate_state",
]
